rm(list=ls())
library(tidyverse)
library(readxl)

source(here::here("code/functions.R"))

#### Read in the DWTP intake grab sample data 
#### (NOTE: 16S data from Sep 16 and 29 not provided/run)

path <- here::here("raw_data/dwtp_grab_samples/2021-qpcr-results.xlsx")
sheets <- readxl::excel_sheets(path)

# Read and tidy 16S data
cp_16s <- read_cp_data(path, sheet = sheets[2]) %>% 
    select(run_date = x1, 
           protocol, sample_id, 
           total_cyano = fam_std_res,
           iac = cy3_std_res,
           contains("ct")) %>% 
  mutate(run_date = as.Date(run_date, "%Y-%m-%d")) 

# Dates of runs where NTC indicated contamination  
ntc_16s <- cp_16s %>% 
  filter(sample_id == "ntc",
         total_cyano != "nd") %>% 
  select(run_date)

cp_16s_raw <- cp_16s %>% 
  filter(!run_date %in% ntc_16s)

# Read and tidy toxin data  
cp_tox <- read_cp_data(path, sheet = sheets[4]) %>% 
  select(run_date = x1, 
         protocol, sample_id, 
         mcye_ndaf = fam_std_res,
         cyra = cy3_std_res,
         sxta = txr_std_res,
         contains("ct")) 

# Dates where NTCs indicated contamination
ntc_tox <- cp_tox %>% 
  filter(sample_id == "ntc") %>% 
  pivot_longer(cols = mcye_ndaf : sxta,
               names_to = "param",
               values_to = "value") %>% 
  filter(value != "nd") %>% 
  select(run_date)
         
cp_tox_raw <- cp_tox %>% 
  filter(!run_date %in% ntc_tox)
         
# Combine and put in long format
cp_complete_long <- cp_16s_raw %>% 
  select(protocol, sample_id, total_cyano) %>% 
  pivot_longer(-c(sample_id, protocol), names_to = "target", values_to = "gu_rxn") %>%
  bind_rows(cp_tox_raw %>%
              select(protocol, sample_id, mcye_ndaf, cyra, sxta) %>% 
              pivot_longer(-c(protocol, sample_id), names_to = "target", values_to = "gu_rxn")
  ) %>% 
  # Convert gene conc. from character to numeric (generates NA warning)
  mutate(gu_rxn = as.numeric(gu_rxn)) %>% 
  mutate(assay = case_when(
    protocol == "cyanodtec_16s" ~ "16s",
    protocol == "cyanodtec_toxin gene" ~ "toxins"
    )) %>% 
  select(-protocol)

# Remove non-samples and format to combine with the rest of the field data
cp_grab_cleaned <- cp_complete_long %>% 
  # Remove all blanks and controls
  filter(str_detect(sample_id, "cp_")) %>% 
  # Add info needed to convert from reaction to sample concentrations 
  mutate(lysis_vol_ul = 500,
         volume_ml = 25,
         rxn_vol_ul = 5) %>% 
  mutate(conc = gu_rxn / rxn_vol_ul * lysis_vol_ul / volume_ml) %>% 
  # Separate sample column into location, month, and day
  separate(sample_id, c("location","month", "day"), sep = "_") %>% 
  # Create a complete date column
  mutate(year = "2021") %>%  
  unite("date", c(day, month, year), sep = "") %>% 
  mutate(date = as.Date(date, "%d%b%Y"),
         location = if_else(location == "cp", "intake", location),
         type = "grab",
         lod = 180,
         frequency = "weekly") %>% 
  select(-c(lysis_vol_ul, volume_ml, rxn_vol_ul, gu_rxn))

## Read in the data from inlet, outlet (passive and grab) and 
## passive samples from DWTP intake
  
# List all the raw qPCR files from the field study
file_list <- list.files(path = here::here("raw_data/qpcr_data"),
                        pattern = "CyanoDTec*")

# Read and clean
field_data_raw <- map(file_list, read_fcn) %>%
  bind_rows() %>% 
  # Separate sample column into location, month, and day
  # (warnings generated by samples not pertinent to the field program)
  separate(sample, c("sample","month", "day"), sep = " ") %>% 
  # Clean up the resulting columns
  mutate(month = str_remove(month, "\\(")) %>% 
  mutate(day = str_remove(day, "\\)")) %>% 
  # Add the target genes for each assay
  mutate(target = case_when(
    (fluor == "cal orange 560" & biological_set_name == "16s rrna") ~ "iac",
    (fluor == "cal orange 560" & biological_set_name == "toxins") ~ "cyra",
    (fluor == "fam" & biological_set_name == "16s rrna") ~ "total_cyano",
    (fluor == "fam" & biological_set_name == "toxins") ~ "mcye_ndaf",
    (fluor == "cal red 610" & biological_set_name == "toxins") ~ "sxta"
  )) %>% 
  # Decode the sample names
  mutate(location = 
           case_when(
             grepl("i", sample) ~ "inlet",
             grepl("o", sample) ~ "outlet",
             sample == "cp" ~ "intake",
             TRUE ~ sample),
         type = case_when(
           grepl("g", sample) ~ "grab",
           grepl("cp", sample) ~ "passive",
           grepl("[a,b]", sample) ~ "passive",
           TRUE ~ NA_character_),
         frequency = 
           case_when(
             location == "intake" ~ "weekly",
             type == "grab" ~ "weekly",
             grepl("a", sample) ~ "weekly",
             grepl("b", sample) ~ "bi-weekly")) %>% 
  # Create a complete date column
  mutate(month = case_when(month == "june"~"jun",
                           month == "july"~"jul",
                           month == "sept"~"sep",
                           TRUE~month),
         year = "2021") %>%  
  unite("date", c(day, month, year), sep = "") %>% 
  mutate(date = as.Date(date, "%d%b%Y")) 

write_csv(field_data_raw, here::here("cleaned_data/field_data_compiled.csv"))

# Get standard curve data
std_data <- field_data_raw %>%
  filter(str_detect(content, "std")) %>%
  filter(!target == "iac") 

# Standard curve results (standards are copies/uL)
curve_results <- std_data %>%
  group_by(target) %>%
  nest() %>%
  # Fit a linear model to each target and tidy the results
  mutate(model = map(data, curve_model)) %>%
  mutate(estimates = map(model, broom::tidy),
         stats = map(model, broom::glance)) %>%
  unnest(c(estimates, stats),
         names_sep = "_") %>% 
  pivot_wider(
    id_cols = c(target, stats_adj.r.squared),
    names_from = estimates_term,
    values_from = estimates_estimate
  ) %>% 
  rename(
    "intercept" = `(Intercept)`,
    "slope" = "log_starting_quantity",
    "r_squared" = stats_adj.r.squared
  ) %>% 
  # Compute the efficiency of each qPCR target
  mutate(efficiency = ((10^(-1 / slope)) - 1) * 100,
         r_squared = round(r_squared, 6)) 

write_csv(curve_results, here::here("output/curve-results.csv"))


# Create the output file with with gene copy concentrations per unit adsorbent
field_data_all <- field_data_raw %>%   
  # Add the standard curve results
  inner_join(curve_results, by = c("target")) %>%
  # Compute the gene copy concentrations per uL in the well
  mutate(gu_well = 10^((cq - intercept) / slope))

# Remove data included in the field program but not from the study lake
field_data_cleaned <- field_data_all %>% 
  filter(location %in% c("inlet", "outlet", "intake")) %>%
  # Add column containing passive sampler area (4.7 cm diameter filter) and grab sample volume (100 mL)
  mutate(area_vol = if_else(type == "passive", 
                            pi*(4.7/2)^2,
                            100)
  ) %>% 
  # Concentration per adsorbent (or grab sample) is gu_well * 500 uL dilution / area or volume
  mutate(conc = gu_well * 500 / area_vol) %>% 
  # Rename and organize
  rename("assay" = `biological_set_name`) %>% 
  arrange(date) %>%
  # Remove low Ct's that are the result of qPCR artefacts
  filter(is.na(cq) | cq > 17) %>% 
  select(date, location, fluor, target, sample, assay, conc, type, frequency) %>%
  # Combine with the DWTP intake grab samples
  bind_rows(., cp_grab_cleaned) %>% 
  # Add LODs (see methods section for details)
  mutate(lod = case_when(
    location == "intake" & type == "grab" ~ 45,
    location %in% c("inlet", "outlet") & type == "grab" ~ 180,
    type == "passive" ~ 260)) %>% 
  # Remove unpaired samples
  filter(date > "2021-07-12") %>%
  select(-c(fluor, sample)) %>% 
  # Some samples were run twice. Keep their mean value
  group_by(date, location, target, type, frequency) %>% 
  summarise(date = head(date),
            location = head(location),
            target = head(target),
            assay = head(assay),
            conc = mean(conc),
            type = head(type),
            frequency = head(frequency),
            lod = mean(lod)
            ) %>% 
  ungroup() %>% 
  distinct(date, location, target, type, frequency, assay, conc, lod)

# Check for duplicates
# field_data_cleaned %>% 
#   group_by(date, location, target, type, frequency) %>% 
#   mutate(n = n()) %>% 
#   filter(n >1) 

write_csv(field_data_cleaned, here::here("cleaned_data/field_data_cleaned.csv"))

plot_data <- field_data_cleaned %>% 
  mutate(
  location = str_to_title(location),
  frequency = str_to_title(frequency),
  type = str_to_title(type),
  target = case_when(
    target == "mcye_ndaf" ~ "mcyE/ndaF",
    target == "total_cyano" ~ "16S rRNA",
    target == "sxta" ~ "sxtA",
    target == "cyra" ~ "cyrA"
  )
) %>%
  mutate(label = case_when(
    target == "mcyE/ndaF" ~ "italic(`mcyE/ndaF`)",
    target == "cyrA" ~ "italic(`cyrA`)",
    target == "sxtA" ~ "italic(`sxtA`)",
    TRUE ~ target
  )) %>%
  mutate(label = factor(label,
                        levels =
                          c(
                            "italic(`mcyE/ndaF`)",
                            "italic(`cyrA`)",
                            "italic(`sxtA`)"
                          )
  )) 

write_csv(plot_data, here::here("cleaned_data/plot_data.csv"))

plot_data %>%
  group_by(date, location, target, type, frequency) %>%
  mutate(n = n()) %>% view()
  filter(n >1)
